baseURL = "https://draescherl.github.io/"
title = "Lucas DRAESCHER"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20
pygmentsStyle = "native"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# disqusShortname = "yourdiscussshortname"

[params]
  author = "Lucas DRAESCHER"
  info = "Cloud Computing engineer in the making | Currently studying at CY-TECH in Pau (France)"
  description = "Lucas' personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "draescherl@cy-tech.fr"

  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  footercontent = ""
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2021
  dateFormat = "January 2, 2006"

  enableTwemoji = false

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/draescherl/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.etude.eisti.fr/draescherl"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/lucas-draescher/?locale=en_US"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
